### ISSUE TITLE
Add Fee Type: Visitacion Valley Facilities & Infrastructure Fee

### ISSUE THREAD

**Issue by adamlodge** [sfcpc/ifc#72] opened 2017-08-31 23:14 UTC
Visitacion Valley Facilities & Infrastructure Fee
http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_420

This fee addresses the impact on infrastructure created by development anticipated in the Visitacion Valley neighborhood.  It applies in the Visitacion Valley Fee Area to all projects that contain 20 or more dwellings and is triggered by either (1)
the addition of a dwelling or (2) the addition of at least 800 square feet of space to a dwelling. In the case of a change of use, fees are lowered to provide credit for existing uses. There are additional options for compliance with this fee, including in-kind provision of infrastructure.

**Comment by chiatt** [comment] 2017-09-07 17:09
@mikewynne Do you know what it means for a project to contain 20 dwellings?  Does it mean that 20 existing dwellings are affected by the project or could it be the removal of 10 and the addition of 10?

**Comment by mikewynne** [comment] 2017-09-07 18:49
@chiatt It probably means a project that adds 20 dwelling units (net) but that is pretty fuzzy language.  Can you send me a link to where in the code that it says this and I'll ask for clarification from our planners.  thanks.

**Comment by chiatt** [comment] 2017-09-07 19:49
Thanks @mikewynne 

Here's the link [Visitacion Fee](http://library.amlegal.com/nxt/gateway.dll/California/planning/article4developmentimpactfeesandprojectr?f=templates$fn=default.htm$3.0$vid=amlegal:sanfrancisco_ca$anc=JD_420)

I pulled the language from the ticket description rather than the code. The code's language is slightly different describing a project that 'has 20 or more residential units' rather than 'contains'.

**Comment by mikewynne** [comment] 2017-09-07 21:48
@chiatt I confirmed with the planners that this mean an **existing** site with 20 residential units.

**Comment by chiatt** [comment] 2017-09-07 21:50
@mikewynne Great - Thanks Mike

**Comment by chiatt** [comment] 2017-10-06 23:20
@robgaston It looks like the fees are all assigned to Mike to QA, but I thought I would give this one to you first so that you have a chance to review the changes I made to the trigger page.

**Comment by mikewynne** [comment] 2018-01-03 18:47
CPC staff who are experts on this fee and are assigned to test the fee. 
Area experts: Doug Vu, Mike Christensen 
General experts: Josephine Chen, Sylvia Jimenez
All-fee experts: Corey Teague, Mat Snyder

**Comment by mikewynne** [comment] 2018-01-19 22:01
Multiple people are reporting that while the fee is calculating correctly it is not always being triggered.  2401 Bay Shore and 5 Leland are examples (both using more than 20 residential units which should trigger the fee).

**Comment by mikewynne** [comment] 2018-02-01 23:45
The fee is not triggering correctly.  It is only being triggered when 20+ EXISTING residential units are entered.  But, it should be triggered whenever the FINAL project is 20+ units (either 20+ new units or adding units to an existing building where the total, existing plus new, is 20+).  

Other than this, the fee is calculating correctly.

**Comment by ryan86** [comment] 2018-02-28 01:17
@mikewynne I reread the code and I don't think this applies to all projects with over 20 units across the board.

```
      (1)   has 20 or more residential units, and
         (A)   creates at least one new residential unit, or
         (B)   creates additional space in an existing residential unit of more than 800 gross square feet.
```

The way I interpret this it seems you could have a project that has >=20 existing units, add no new units, and add only 400gsf and the fee would not be triggered.

The trigger calculation should reflect this now.

**Comment by mikewynne** [comment] 2018-03-05 18:13
@ryan86 I agree.  The fee looks good.  Thanks.

**Closed** 2018-03-05 22:35 UTC
Labels: Neighborhood-Specific
